class Strings {
  static const Map<String, Map<String, String>> _data = {
    'ar': {
      'appName': 'شركة فاوري',
      'appNameSub': 'شركة فاوري | Fawori Company',
      'home': 'الرئيسية', 'products': 'المنتجات', 'wallet': 'المحفظة',
      'favorites': 'المفضلة', 'settings': 'الإعدادات', 'gifts': 'الهدايا',
      'quickAccess': 'الوصول السريع', 'certifiedAgents': 'وكلاء معتمدون',
      'productsAndGifts': 'المنتجات والهدايا', 'searchProduct': 'ابحث باسم المنتج',
      'all': 'الكل', 'primers': 'الاساسات', 'interior': 'طلائات داخلية',
      'exterior': 'طلائات خارجية', 'noProducts': 'لا توجد منتجات',
      'giftsSoon': 'قسم الهدايا — سيُبنى حسب شرحك لاحقاً',
      'language': 'اللغة', 'darkMode': 'الوضع الداكن', 'about': 'حول التطبيق',
      'logout': 'تسجيل خروج', 'version': 'الإصدار 1.0.0',
      'aboutText': 'تطبيق شركة فاوري لعرض المنتجات والهدايا والوكلاء المعتمدين.',
      'ok': 'حسناً', 'confirmLogout': 'هل أنت متأكد من أنك تريد تسجيل الخروج؟',
      'yes': 'نعم', 'no': 'لا', 'noFavorites': 'لا توجد منتجات في المفضلة بعد',
      'walletSoon': 'هذه الصفحة نبنيها حسب شرحك لاحقاً',
      'accountType': 'نوع الحساب', 'agent': 'وكيل', 'tech': 'فني',
      'phoneNumber': 'رقم الهاتف', 'password': 'كلمة المرور',
      'login': 'تسجيل الدخول', 'noAccount': 'لا تملك حساباً؟', 'signUp': 'سجل الآن',
      'brand_fawori': 'فاوري', 'brand_isomat': 'آيزومات',
      'brand_cadence': 'كادينز', 'brand_sibax': 'سيباكس',
      'createAccount': 'إنشاء حساب',
      'contactAgentPart': 'يرجى التواصل مع الوكيل الخاص بك لإنشاء حساب، أو يمكنك المتابعة كـ',
      'guest': 'ضيف', 'continueAsGuest': 'المتابعة كضيف', 'cancel': 'إلغاء',
      'lockedTitle': 'ميزة مقفلة',
      'lockedMsg': 'هذه الميزة متاحة للحسابات المسجلة فقط، تواصل مع الوكيل الخاص بك.',
      'adminPanel': 'لوحة المدير', 'enterToken': 'أدخل توكن GitHub',
      'tokenSaved': 'تم حفظ التوكن محلياً', 'changeToken': 'تغيير التوكن',
      'save': 'حفظ', 'savedRebuild': 'تم الحفظ — سيُعاد بناء التطبيق تلقائياً خلال دقائق',
      'loading': 'جارٍ التحميل...',
    },
    'en': {
      'appName': 'Fawori Company',
      'appNameSub': 'Fawori Company | شركة فاوري',
      'home': 'Home', 'products': 'Products', 'wallet': 'Wallet',
      'favorites': 'Favorites', 'settings': 'Settings', 'gifts': 'Gifts',
      'quickAccess': 'Quick Access', 'certifiedAgents': 'Certified Agents',
      'productsAndGifts': 'Products & Gifts', 'searchProduct': 'Search by product name',
      'all': 'All', 'primers': 'Primers', 'interior': 'Interior Paints',
      'exterior': 'Exterior Paints', 'noProducts': 'No products',
      'giftsSoon': 'Gifts section — coming soon',
      'language': 'Language', 'darkMode': 'Dark mode', 'about': 'About',
      'logout': 'Logout', 'version': 'Version 1.0.0',
      'aboutText': 'Fawori Company app for products, gifts and certified agents.',
      'ok': 'OK', 'confirmLogout': 'Are you sure you want to log out?',
      'yes': 'Yes', 'no': 'No', 'noFavorites': 'No favorites yet',
      'walletSoon': 'This page is coming soon',
      'accountType': 'Account type', 'agent': 'Agent', 'tech': 'Technician',
      'phoneNumber': 'Phone number', 'password': 'Password',
      'login': 'Login', 'noAccount': "Don't have an account?", 'signUp': 'Sign up now',
      'brand_fawori': 'Fawori', 'brand_isomat': 'Isomat',
      'brand_cadence': 'Cadence', 'brand_sibax': 'Sibax',
      'createAccount': 'Create Account',
      'contactAgentPart': 'Please contact your agent to create an account, or continue as a',
      'guest': 'guest', 'continueAsGuest': 'Continue as guest', 'cancel': 'Cancel',
      'lockedTitle': 'Locked Feature',
      'lockedMsg': 'This feature is for registered accounts only. Contact your agent.',
      'adminPanel': 'Admin Panel', 'enterToken': 'Enter GitHub token',
      'tokenSaved': 'Token saved locally', 'changeToken': 'Change token',
      'save': 'Save', 'savedRebuild': 'Saved — the app will rebuild automatically in minutes',
      'loading': 'Loading...',
    },
  };

  static String get(bool arabic, String key) =>
      _data[arabic ? 'ar' : 'en']?[key] ?? key;
}
